#!/bin/bash

#
#
#    Dnscrypt-proxy-selector
#	   1.0.7-1B (4th Build)    previous version = 1.0.7C(3rd Build)
#	Allows You To Select Which Proxy dns To Use.
#
#	"Darken the city night is awire , steam in the subway earth is afire." - duran duran
#	Created By Joshua Adam Leigh Chambers (c)2017 
#	open-source edit where applicable. do keep a note of original creator.
#

dnscryptproxylist="/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv"
originalscriptURL="https://github.com/josh788/dnscrypt-proxy-selector/"
githubpageURL="https://josh788.github.io/dnscrypt-proxy-selector/"
previousVersion="1.0.7C (Third-Design)"

function Startup {
clear
tput setaf 6
tput bold
echo "─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────"
echo "─██████████████─██████████████─██████─────────██████████████─██████████████─██████████████─██████████████─████████████████───"
echo "─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██─────────██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░░░██───"
echo "─██░░██████████─██░░██████████─██░░██─────────██░░██████████─██░░██████████─██████░░██████─██░░██████░░██─██░░████████░░██───"
echo "─██░░██─────────██░░██─────────██░░██─────────██░░██─────────██░░██─────────────██░░██─────██░░██──██░░██─██░░██────██░░██───"
echo "─██░░██████████─██░░██████████─██░░██─────────██░░██████████─██░░██─────────────██░░██─────██░░██──██░░██─██░░████████░░██───"
echo "─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██─────────██░░░░░░░░░░██─██░░██─────────────██░░██─────██░░██──██░░██─██░░░░░░░░░░░░██───"
echo "─██████████░░██─██░░██████████─██░░██─────────██░░██████████─██░░██─────────────██░░██─────██░░██──██░░██─██░░██████░░████───"
echo "─────────██░░██─██░░██─────────██░░██─────────██░░██─────────██░░██─────────────██░░██─────██░░██──██░░██─██░░██──██░░██─────"
echo "─██████████░░██─██░░██████████─██░░██████████─██░░██████████─██░░██████████─────██░░██─────██░░██████░░██─██░░██──██░░██████─"
echo "─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─────██░░██─────██░░░░░░░░░░██─██░░██──██░░░░░░██─"
echo "─██████████████─██████████████─██████████████─██████████████─██████████████─────██████─────██████████████─██████──██████████─"
echo "─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────"
tput setaf 1
echo "──────────────────────────────────────────────────[ DNSCRYPT-PROXY-SELECTOR ]────────────────────────────────────────────────"
echo "                                                           1.0.7-1B                                                            "
echo ""
echo "[───────────────────────[MENU]───────────────────────────]"
tput setaf 6
echo "[ 1) Select & connect                                    ]"
echo "[ 2) Check if running                                    ]"
echo "[ 3) Check DNS using [http://www.dnsleaktest.com/]       ]"
echo "[ 4) Changes since Last Version release                  ]"
echo "[ 5) Update Proxy List                                   ]"
echo "[ 6) Exit                                                ]"
tput setaf 1
echo "[───────────────────────[MENU]───────────────────────────]"
tput setaf 6
read option;
checkd
}

function checkd {

if [ $option == "1" ]
then
S-C
elif [ $option == "2" ]
then
netstat -tulpn | grep :53
echo "press enter when ready."
read enterkey;
clear
Startup
elif [ $option == "3" ]
then
sensible-browser http://www.dnsleaktest.com/ &
elif [ $option == "4" ]
then
echo "[─────────────────────── [Changes] ───────────────────────]"
echo " Added Update Function To Allow Update To Be Made.         "
echo "───────────────────────────────────────────────────────────"
echo " Fix To Check Dns Option , now Runs In The Background.     "
echo "───────────────────────────────────────────────────────────"
echo " New In 1.0.5B : Fix To The S-C Function Means you can     "
echo " Find Your selected Proxy At 127.0.0.1:53.                 "
echo ""
echo "───────────────────────────────────────────────────────────"
echo " Implementation of option to check that your dns is        "
echo " Configured and Working Properly.                          "
echo ""
echo "[─────────────────────────────────────────────────────────]"
echo "Press Enter To Continue."
read enterkey;
Startup
elif [ $option == "5" ]
update-list
elif [ $option == "6" ]
then
echo "Exiting..."
clear
exit
else 
echo "Invalid Option."
echo "press enter to go back."
read enterkey;
Startup
fi
}

function S-C {

column -s, -t < $dnscryptproxylist | less -#2 -N -S
echo "please enter the name of the proxy : cs-ch "
read resolvername;

/usr/sbin/dnscrypt-proxy -a 127.0.0.1 -d -R $resolvername 
netstat -tulpn | grep :53
echo "if you can see 127.0.0.1:53 then your all set. :)"
echo "press enter to return to the menu."
read enterkey;
Startup

}

function update-list {

echo "[─────────────────────────────────────────────────────────]"
echo " Updating proxy List...."
wget -P /usr/share/dnscrypt-proxy/ https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-resolvers.csv
echo "Saving to /usr/share/dnscrypt-proxy/ ..."
echo "Done! Press enter to Return To The Menu."
echo "[─────────────────────────────────────────────────────────]"
read null;
startup
}


Startup
